from typing import Any

_C_OUT: Any
_C_PTR: Any
_C_LNG: Any

def lookUpClass(name: str) -> Any: ...
def selector(name: str) -> Any: ...
def registerMetaDataForSelector(*args: Any, **kwargs: Any) -> Any: ...

class NSObject:
    def alloc(self) -> Any: ...
    def init(self) -> Any: ...
    def respondsToSelector_(self, selector: Any) -> bool: ...

class objc_object:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __int__(self) -> int: ...
    def respondsToSelector_(self, selector: Any) -> bool: ...
    def subviews(self) -> Any: ...
    def superview(self) -> Any: ...
    def window(self) -> Any: ...

def super(*args: Any, **kwargs: Any) -> Any: ...
