from typing import Any

kCVPixelFormatType_32BGRA: Any
kCVPixelBufferCGImageCompatibilityKey: Any
kCVPixelBufferCGBitmapContextCompatibilityKey: Any

def CVPixelBufferCreate(*args: Any, **kwargs: Any) -> tuple[Any, Any]: ...
def CVPixelBufferLockBaseAddress(*args: Any, **kwargs: Any) -> Any: ...
def CVPixelBufferGetBytesPerRow(*args: Any, **kwargs: Any) -> Any: ...
def CVPixelBufferGetBaseAddress(*args: Any, **kwargs: Any) -> Any: ...
def CVPixelBufferUnlockBaseAddress(*args: Any, **kwargs: Any) -> Any: ...
